### PR TITLE
Add testing steps section

### PR DESCRIPTION
**Pull request by Stypox**
This PR adds a section with the steps to take in order to fully test the app, as lately some things have been forgotten and some bugs were not noticed in the testing phase. Since there are many many things to be written, I would appreciate some help. For now I only added some basic test steps for activities.

### CODE REVIEW

**Comment by wb9688** [comment]
@opusforlife2: Maybe you're interested in helping with this?

**Comment by opusforlife2** [comment]
I feel so loved. :3

Alright, firstly, does manual testing have to include every possible action that a user can take? Or are some things handled by automated tests?

Second, if the tests turn out to be as numerous as I'm imagining, it would be good to recruit some testers and assign specific categories for them to test so that there is little burden on one person.

**Comment by wb9688** [comment]
@opusforlife2: NewPipe has some automated testing, but it's very limited, see https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/androidTest/java/org/schabi/newpipe and https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/test/java/org/schabi/newpipe

**Comment by Stypox** [comment]
Automated tests would not be a bad idea, even though I know nothing about them: https://developer.android.com/training/testing/ui-testing

**Comment by wb9688** [comment]
We shouldn't make the automated tests dependent on NewPipeExtractor though, but mock (all cases! e.g. SoundCloud only has audio streams, so that's handled differently in the front-end) that where neccesary.

**Comment by opusforlife2** [comment]
What about languages? Some users report bugs that only occur for specific languages.

**Comment by wb9688** [comment]
@opusforlife2: If you mean those crashes for e.g. Polish recently, that's now caught by manually running Android's Lint before release. If you mean country/language-specific issues with extracting stuff, I personally consider that out of scope here.

**Comment by opusforlife2** [comment]
So, is there a consensus about how much should be automated and how much should be manual testing?

**Comment by Stypox** [comment]
As of now all possible manual actions have to be tested manually before release, since there is no automatic testing in place, so this list should contain all of those (@opusforlife2 you seem to be able to find and check every possible action under any configuration ;-) ). This list could then be used before merging a big PR or before releasing a new version. I'm going to contribute more to this in the following weeks, but any help would be appreciated :-)

**Comment by Stypox** [comment]
The latter

**Pull request closed without merging**
