### PR TITLE
Migrate to github actions from travis CI

### PR DESCRIPTION
**Pull request by XiangRongLin**
- https://github.com/actions/setup-python

currently testing it: https://github.com/XiangRongLin/documentation/pull/1

### CODE REVIEW

**Comment by XiangRongLin** [comment]
This can only be done after #33

**Comment by TheAssassin** [comment]
I could imagine it's much easier to just run your commands in a `python:3` Docker image. Mind if I try that out?

**Comment by XiangRongLin** [comment]
Feel free to take over. I added some stuff that o could fix quickly (and dirty).

---

I managed to run it locally after i figured out to install the dependencies in user mode, meaning using `pip install --user`.

Before that i was using nectos/act but that took way to long

**Comment by TheAssassin** [comment]
I'll add a shell script that is going to allow you to run it locally as the CI would. This is a pattern I use in most repositories. Being able to reproduce results locally is important.

**Comment by XiangRongLin** [comment]
That what i use https://github.com/nektos/act for. But it's big and compativly slow

**Comment by TheAssassin** [comment]
I guess we have to merge this initially in order to see if it works. In my temporary fork, it looks good, though.

For the record: this is one of the reasons I love sphinx-doc. It provides this feature out of the box.

**Review by TheAssassin — APPROVED** [review]

**Comment by XiangRongLin** [comment]
@TheAssassin I collected the problems i have found in #33. Of the 2 remaining problems, only 4 is critical in order to have the CI pipeline run successfully.
The script probably needs to adjusted so that it either
1. reads in all files at the start (con: growing memory load, should be ok with the current 64kB)
2. or load the referenced file when needed (con: same file gets loaded multiple times)
so one can check references to other files.

I would be in favor of 1

**Comment by TheAssassin** [comment]
Either will work. There is really no performance optimization required. I mean, if you really wanted, you could implement a lazy loader that caches the contents...

**Pull request merged**
